<a href="https://colab.research.google.com/github/tushar2k/Sem-V-labs/blob/master/DL-%20ECSE440L/DL_Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
np.version.version

'1.18.5'

In [ ]:
arr1= np.array([[1,2,3],[3,4,5]]) #integer array
arr2= np.array([[1,2.0,3.3],[3,4,5.5]]) #float array
arr3 = np.array( [ [ 4 , 8 ] , [ 3 , 8 ] ], dtype=complex ) #complex array

In [ ]:
print("Data type of \n", arr1,arr1.dtype)
print("Data type of \n", arr2,arr2.dtype)
print("Data type of \n", arr3,arr3.dtype)

Data type of 
 [[1 2 3]
 [3 4 5]] int64
Data type of 
 [[1.  2.  3.3]
 [3.  4.  5.5]] float64
Data type of 
 [[4.+0.j 8.+0.j]
 [3.+0.j 8.+0.j]] complex128


In [ ]:
print("Shape type of \n", arr1,arr1.shape)
print("Shape type of \n", arr2,arr2.shape)
print("Shape type of \n", arr3,arr3.shape)

Shape type of 
 [[1 2 3]
 [3 4 5]] (2, 3)
Shape type of 
 [[1.  2.  3.3]
 [3.  4.  5.5]] (2, 3)
Shape type of 
 [[4.+0.j 8.+0.j]
 [3.+0.j 8.+0.j]] (2, 2)


In [ ]:
print("Dimension type of \n", arr1,arr1.ndim)
print("Dimension type of \n", arr2,arr2.ndim)
print("Dimension type of \n", arr3,arr3.ndim)

Dimension type of 
 [[1 2 3]
 [3 4 5]] 2
Dimension type of 
 [[1.  2.  3.3]
 [3.  4.  5.5]] 2
Dimension type of 
 [[4.+0.j 8.+0.j]
 [3.+0.j 8.+0.j]] 2


In [ ]:
 matrix1 = np.arange(10,22).reshape(4,3)
 matrix2 = np.arange(12).reshape(4,3)
 print (matrix1, '\n\n', matrix2, '\n\n', matrix1+matrix2)

[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]] 

 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 

 [[10 12 14]
 [16 18 20]
 [22 24 26]
 [28 30 32]]


In [ ]:
print(matrix1.transpose(),matrix1.transpose().shape)

[[10 13 16 19]
 [11 14 17 20]
 [12 15 18 21]] (3, 4)


In [ ]:
print(matrix1, '\n*\n', matrix1 , '\n=\n', matrix1*matrix1)

[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]] 
*
 [[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]] 
=
 [[100 121 144]
 [169 196 225]
 [256 289 324]
 [361 400 441]]


In [ ]:
print(matrix1, '\n.\n', matrix1.transpose() , '\n=\n', matrix1.dot(matrix1.transpose()))

[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]] 
.
 [[10 13 16 19]
 [11 14 17 20]
 [12 15 18 21]] 
=
 [[ 365  464  563  662]
 [ 464  590  716  842]
 [ 563  716  869 1022]
 [ 662  842 1022 1202]]


In [ ]:
for i in range(len(matrix1)):
    for j in range (len(matrix1[0])):
        print (matrix1[i][j], end=", ")
    print()

10, 11, 12, 
13, 14, 15, 
16, 17, 18, 
19, 20, 21, 


In [ ]:
print (matrix1[0],'\nafter reversing'+'\n',matrix1[0][::-1])

[10 11 12] 
after reversing
 [12 11 10]


In [ ]:
from numpy import genfromtxt

In [ ]:
df = genfromtxt('/content/AMZN.csv', delimiter=',')

In [ ]:
print(df)
print(df.ndim)
print(df.shape)
print(df.size)
print(type(df))

[[           nan            nan            nan ...            nan
             nan            nan]
 [           nan 1.81450000e+03 1.81681995e+03 ... 1.80138000e+03
  1.80138000e+03 1.92950000e+06]
 [           nan 1.81939001e+03 1.82957996e+03 ... 1.82354004e+03
  1.82354004e+03 2.03180000e+06]
 ...
 [           nan 3.21200000e+03 3.32000000e+03 ... 3.31248999e+03
  3.31248999e+03 5.34600000e+06]
 [           nan 3.30301001e+03 3.31589990e+03 ... 3.26047998e+03
  3.26047998e+03 4.16710000e+06]
 [           nan 3.25200000e+03 3.30470996e+03 ... 3.30288501e+03
  3.30288501e+03 2.29529100e+06]]
2
(255, 7)
1785
<class 'numpy.ndarray'>
